# Site settings
title: wingadium 
email: wingadium1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  testbed for case study publication
url: http://wingadium1.github.io" # the base hostname & protocol for your site
twitter_username: wingadium1
github_username:  wingadium1
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap